// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-fYZoglray6zSJH9gc6OplPkLH6fYoVE',
    appId: '1:111193467747:web:ad7f4cf33440e5e3fe0156',
    messagingSenderId: '111193467747',
    projectId: 'sugar-tracker-93c4c',
    authDomain: 'sugar-tracker-93c4c.firebaseapp.com',
    storageBucket: 'sugar-tracker-93c4c.firebasestorage.app',
    measurementId: 'G-Q980YHMXCC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlrX1xlfzeMAoKOPrjdSi4dkNQfGE7_ys',
    appId: '1:111193467747:android:77720f331ca7fb10fe0156',
    messagingSenderId: '111193467747',
    projectId: 'sugar-tracker-93c4c',
    storageBucket: 'sugar-tracker-93c4c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNz6qs4ETiQxDWLt1I8FKWys0PXb4ZFXg',
    appId: '1:111193467747:ios:cd00a05cb914ca77fe0156',
    messagingSenderId: '111193467747',
    projectId: 'sugar-tracker-93c4c',
    storageBucket: 'sugar-tracker-93c4c.firebasestorage.app',
    iosBundleId: 'com.example.sugarTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNz6qs4ETiQxDWLt1I8FKWys0PXb4ZFXg',
    appId: '1:111193467747:ios:cd00a05cb914ca77fe0156',
    messagingSenderId: '111193467747',
    projectId: 'sugar-tracker-93c4c',
    storageBucket: 'sugar-tracker-93c4c.firebasestorage.app',
    iosBundleId: 'com.example.sugarTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB-fYZoglray6zSJH9gc6OplPkLH6fYoVE',
    appId: '1:111193467747:web:9b71ff680fcacfccfe0156',
    messagingSenderId: '111193467747',
    projectId: 'sugar-tracker-93c4c',
    authDomain: 'sugar-tracker-93c4c.firebaseapp.com',
    storageBucket: 'sugar-tracker-93c4c.firebasestorage.app',
    measurementId: 'G-VLYGJF443E',
  );
}
